default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: NoteDevelopment


test:
  <<: *default
  database: NoteTest

production:
   <<: *default
   adapter: postgresql
   database: NoteProduction