# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 856aeb481dd65360d1a791f767ecf3d3401b53e219a009d619729dc9a46be4e9e3e753c6e90ab41eaea25245fe4478d0961a9df9438890759413460318e40f44

test:
  secret_key_base: 8967d1f0ce36d68fc0c8a2ec73a74cb1bcea193b871599830cbceb639c802c115c898806db41fba3708984ab346a4c377bbb60d0bdf3f4407af178bbb66c4d0b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
